### ISSUE TITLE
Not compressing non-nes games

### ISSUE THREAD

**Issue by tjm694** [elierodrigue/Hakchi_HelpingHand#3]
I have a few non-nes games (96) in fact, that it says "compressing" then shows "not compressed" each time I run it.   Any ideas?

**Comment by KMFDManic** [comment]
Only works on hakchi2 version 2.14/2.15/2.16. And, even though it says "not compressed".  You can close hakchi2, reopen it, then look at the command line for the nes games to see if they properly 7zipped.  Remember, use option 4.

**Comment by tjm694** [comment]
I said, NON-NES games ....

**Comment by KMFDManic** [comment]
My statement still holds true.  But, what specific game systems are not compressing?

**Comment by tjm694** [comment]
Atari, Genesis, SNES, GB, GBC, SMS, etc.  Everything that's not .NES.   I could've compressed them before I added them, but I did not.   Either way, there is 96 of them not compressed.

**Comment by KMFDManic** [comment]
All of those specific systems compress to 7zip automatically in normal hakchi2 if you have compress-non nes games option enabled when adding them, with exception of atari 2600.  Atari is so small, even with a full set, you would gain only 1.5 mb from compression.

**Comment by KMFDManic** [comment]
Helping hand was meant mainly for NES compression.  Hakchi2 handles other systems, already.  He would have to add code revision to allow other systems to compress.  But, there is no guarantee it would be priority, since hakchi2 handles that process, as is.

**Comment by tjm694** [comment]
Yeah I know it was ... but I figured it SHOULD hit the rest if it sees it.  NO biggie, I was just curious,

**Comment by KMFDManic** [comment]
Yeah, just 96 games.  Not too bad.  I initially devised the compression technique that is used in helping hand, 2 months ago.  So, when he posted version 1.0, it was easy for me to pinpoint his missed command line arguments, since I had already done them 2 months ago, heh.  Compression was something I did moment Retroarch was released, first day.  I have 2000 games with my setup, currently.

**Comment by elierodrigue** [comment]
Give a try to 1.2, I fixed a compression issue.
