### ISSUE TITLE
C8/C2 Error

### ISSUE THREAD

**Issue by ghost** [elierodrigue/Hakchi_HelpingHand#6]
Took my NESC, uninstalled Hakchi2 (reverting back to stock), and performed a fresh install of Hakchi2 v2.16c after using  Helping Hand to compress game files. After installation I ran the save cache clearing fix, hooked my NESC back up to my HDTV, and tried my newly modded NESC for the first time. First folder transition took about 30 seconds. When the menu came back up, I selected a game (a game that had been added). The menu dimmed like it was going to start the game, but came right back to the menu. Tried another game. Same thing. Did this a few more times before I decided to check one of the default 30 games. So I chose Castlevania. Screen went black, then after a minute or two, I figured something was wrong, and pressed the power button. Immediately a C8 error popped up. I then depressed the power button twice to shut off the console. When I powered it back up, I got the C2 error.

Once I selected the language, I tried Castlevania II. Game came up like it should. Then tried Castlevania. No problem. Mega man II? No issue. Then tried a game I added, the menu dimmed and came right back to the menu. Another added game? Same thing.

So the original 30 games work, but none of the added games work. These are games I can verify worked on Hakchi2 v2.16 prior to my usage of Helping Hand.

Is it a problem with Helping Hand's compression function or is the save cache clearing function removing something required for these games to play?

[Added...]

Okay, I think it's something with the "compress games" function. I just reverted back to stock, did a fresh install of Hakchi2 v2.16, and used Helping Hand for the save cache clearing function only. Added games appear to be working now.

And I did the same disconnect/reconnect technique to get Helping Hand to recognize that my NESC was connected. Connection established on the first try.

**Comment by elierodrigue** [comment]
Did you installed Retroarch? Its required for zipped games to work : 
https://github.com/ClusterM/retroarch-clover/releases

**Comment by ghost** [comment]
Ah, no. I've only been using my NESC for NES games, so I hadn't worried about Retroarch.

If Retroarch is required, then I'll just skip the compressing games function. Since I'm only using NES games, I have a fair amount of unused storage space that uncompressed files shouldn't be an issue. Just thought it'd make for a tidier setup.

Sorry for the trouble.
